import mongoose from "mongoose";

const reportSchema = new mongoose.Schema(
  {
    workspaceId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Workspace",
      required: true,
      index: true,
    },
    title: { type: String, required: true },
    periodStart: { type: Date, required: true },
    periodEnd: { type: Date, required: true },

    // Structured content generated by the AI report service (Day 25)
    contentJson: {
      topThemes: [
        {
          name: String,
          count: Number,
          deltaPct: Number,
        },
      ],
      sentimentShift: {
        positivePct: Number,
        neutralPct: Number,
        negativePct: Number,
        deltaFromPreviousPeriodPct: Number,
      },
      notableQuotes: [
        {
          quote: String,
          channel: String,
          sentiment: String,
        },
      ],
      recommendedActions: [String],
      narrative: String, // AI-written prose summary
    },

    generatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
  },
  { timestamps: true }
);

reportSchema.index({ workspaceId: 1, createdAt: -1 });

const Report = mongoose.model("Report", reportSchema);

export default Report;
