// Realistic sample feedback used to seed demo workspaces and to power the
// "simulate channel" ingestion buttons (Day 11). At least 20+ items per
// channel so the seed script comfortably exceeds the 120-item minimum.

export const SAMPLE_CHANNEL_FEEDBACK = {
  support_ticket: [
    { content: "Onboarding took forever — I couldn't figure out how to invite my team.", customerLabel: "Acme Corp" },
    { content: "Billing page keeps timing out when I try to download an invoice.", customerLabel: "Northwind" },
    { content: "Getting a 500 error every time I try to export my report to CSV.", customerLabel: "Globex" },
    { content: "Support response time has been over 48 hours for a critical bug.", customerLabel: "Initech" },
    { content: "The mobile app logs me out every few hours, very frustrating.", customerLabel: "Umbrella Inc" },
    { content: "Can't reset my password — the reset email never arrives.", customerLabel: "Stark Industries" },
    { content: "Dashboard loads painfully slowly with more than 10k rows of data.", customerLabel: "Wayne Enterprises" },
    { content: "SSO login is broken after your last deploy, whole team is locked out.", customerLabel: "Hooli" },
    { content: "Notifications aren't being delivered to Slack anymore.", customerLabel: "Pied Piper" },
    { content: "Bulk delete silently failed and left orphaned records behind.", customerLabel: "Soylent Corp" },
    { content: "API rate limits are too aggressive for our usage pattern.", customerLabel: "Cyberdyne" },
    { content: "Search is returning stale results, doesn't reflect recent edits.", customerLabel: "Massive Dynamic" },
    { content: "We keep getting duplicate notification emails for the same event.", customerLabel: "Aperture Science" },
    { content: "Two-factor auth codes never arrive via SMS.", customerLabel: "Tyrell Corp" },
    { content: "The audit log doesn't capture who changed a record's status.", customerLabel: "Oscorp" },
    { content: "File uploads fail silently above 10MB with no error message.", customerLabel: "Gekko & Co" },
    { content: "Permissions aren't respected — a viewer role could edit a record.", customerLabel: "Wonka Industries" },
    { content: "Timezone settings don't apply to scheduled report emails.", customerLabel: "Bluth Company" },
    { content: "Webhook deliveries are randomly dropped without retry.", customerLabel: "Dunder Mifflin" },
    { content: "Support macros reference an old UI that no longer matches the product.", customerLabel: "Prestige Worldwide" },
  ],
  app_store_review: [
    { content: "The new dashboard is gorgeous and finally fast. Huge improvement.", customerLabel: "5-star review" },
    { content: "Love the redesign but wish dark mode was the default.", customerLabel: "4-star review" },
    { content: "Crashes every time I try to attach a photo to a ticket.", customerLabel: "1-star review" },
    { content: "Best feedback tool we've used, the AI summaries save us hours.", customerLabel: "5-star review" },
    { content: "Great app, but onboarding for new team members is confusing.", customerLabel: "3-star review" },
    { content: "Search feels much snappier since the last update, nice work.", customerLabel: "5-star review" },
    { content: "Wish there was a proper offline mode for the mobile app.", customerLabel: "3-star review" },
    { content: "Constant login prompts on iOS, very annoying.", customerLabel: "2-star review" },
    { content: "The charts are beautiful and finally exportable as images.", customerLabel: "5-star review" },
    { content: "App froze completely during CSV import, had to force close.", customerLabel: "1-star review" },
    { content: "Customer support responded within minutes, impressed.", customerLabel: "5-star review" },
    { content: "Would love keyboard shortcuts for power users.", customerLabel: "4-star review" },
    { content: "Push notifications are delayed by hours sometimes.", customerLabel: "2-star review" },
    { content: "The new theming/trends view is exactly what our PM team needed.", customerLabel: "5-star review" },
    { content: "Too many clicks to triage a single feedback item.", customerLabel: "3-star review" },
    { content: "Pricing is fair for the value, switched from a competitor happily.", customerLabel: "5-star review" },
    { content: "Ask LOOP gave me a wrong answer that wasn't grounded in real data once.", customerLabel: "2-star review" },
    { content: "Export to PDF for reports looks very professional, clients loved it.", customerLabel: "5-star review" },
  ],
  nps_survey: [
    { content: "It does the job, but the mobile experience needs work.", customerLabel: "NPS: 6" },
    { content: "We'd recommend this to other product teams, saves real time weekly.", customerLabel: "NPS: 9" },
    { content: "Great analytics, but I want more granular date filtering.", customerLabel: "NPS: 8" },
    { content: "Honestly considering switching due to slow load times lately.", customerLabel: "NPS: 3" },
    { content: "The AI classification accuracy has been consistently impressive.", customerLabel: "NPS: 10" },
    { content: "Missing a way to bulk-tag feedback items, doing it one by one is tedious.", customerLabel: "NPS: 5" },
    { content: "Reports are the best part of the product, leadership loves them.", customerLabel: "NPS: 9" },
    { content: "Setup was painless, we were live in under an hour.", customerLabel: "NPS: 8" },
    { content: "Would like Zapier or native Slack integration for alerts.", customerLabel: "NPS: 7" },
    { content: "Too expensive for teams under 5 people, price scaling is off.", customerLabel: "NPS: 4" },
    { content: "Ask LOOP has genuinely changed how we run product meetings.", customerLabel: "NPS: 10" },
    { content: "Inbox filtering could use saved views / segments.", customerLabel: "NPS: 6" },
  ],
  sales_call_note: [
    { content: "Prospect wants SSO before they'll sign — third time this month.", customerLabel: "Deal: Vandelay Industries" },
    { content: "Champion asked for a Salesforce integration during the demo.", customerLabel: "Deal: Gringotts" },
    { content: "Buyer loved the Ask LOOP demo, said it's a clear differentiator.", customerLabel: "Deal: Stark Industries" },
    { content: "Procurement flagged our data retention policy as a blocker.", customerLabel: "Deal: Wayne Enterprises" },
    { content: "Customer wants a custom report template for their board deck.", customerLabel: "Deal: Hooli" },
    { content: "Competitor is undercutting us on price for the enterprise tier.", customerLabel: "Deal: Cyberdyne" },
    { content: "They specifically asked whether we support on-prem deployment.", customerLabel: "Deal: Umbrella Inc" },
    { content: "Trial team hit the workspace member limit and got frustrated.", customerLabel: "Deal: Aperture Science" },
    { content: "Renewal at risk — they say the mobile app is a dealbreaker.", customerLabel: "Deal: Oscorp" },
    { content: "Upsell opportunity: they want the AI report feature on a lower tier.", customerLabel: "Deal: Massive Dynamic" },
  ],
  social_mention: [
    { content: "Love the new export feature, saved me an hour today.", customerLabel: "Twitter/X mention" },
    { content: "Anyone else notice the app got way faster this week? Nice.", customerLabel: "Reddit thread" },
    { content: "Support ticket from last month still hasn't been resolved, disappointing.", customerLabel: "Twitter/X mention" },
    { content: "Just discovered the Ask LOOP feature, it's basically magic for PMs.", customerLabel: "LinkedIn post" },
    { content: "Their pricing page is confusing, took me a while to find enterprise info.", customerLabel: "Reddit thread" },
    { content: "Big shoutout to their support team for a same-day fix.", customerLabel: "Twitter/X mention" },
    { content: "Dashboard redesign is a big step up visually.", customerLabel: "LinkedIn post" },
    { content: "Wish the community had more example report templates to copy.", customerLabel: "Reddit thread" },
  ],
};

export default SAMPLE_CHANNEL_FEEDBACK;
